### ISSUE TITLE
[Bug]: Typo in Auth Flow

### ISSUE THREAD

**Issue by jake-smith** [Scalr/scalr-vscode#14]
**Describe the bug**

Just a small typo in the auth flow.

”Peast” instead of “Paste” when Authenticating in VS Code.

**To Reproduce**

1. Go to Scalr Extension
2. Click on 'Login'
3. See error in command window "Peast an existing token..."

**Expected behavior**

**Screenshots**

![scalr_vs_code](https://github.com/user-attachments/assets/75ab1879-dc76-4ae3-91ba-00a0081a1365)

**Extension Version (please complete the following information):**

-   Version: [e.g. v1.0.0]

**VSCode Version:**

-   Version: [e.g. 1.78.2]

**OS:**

-   OS: [e.g. Windows 10, macOS 13.3]

**Additional context**

**Comment by emocharnik** [comment]
Hi, @jake-smith! Thanks for the request. We'll fix it in the nearest release.
