### ISSUE TITLE
[Feature]: Web-Compatible Extension

### ISSUE THREAD

**Issue by pbnj-dragon** [Scalr/scalr-vscode#23]
**Is your feature request related to a problem? Please describe.**

Currently, the Scalr extension is only available for desktop vscode. 

When developers use [VS Code for the Web](https://code.visualstudio.com/docs/editor/vscode-web) (i.e. press `.` on a github repo, visiting https://vscode.dev or https://github.dev, using GitHub Codespaces), the Scalr extension is unavailable [^1].

**Describe the solution you'd like**

Make the Scalr extension compatible with web-based VSCode, per [Web Extensions Developer Guide](https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-enablement).

**Describe alternatives you've considered**

N/A

**Additional context**

[^1]: ![image](https://github.com/user-attachments/assets/af591b60-8823-4075-8b27-dadee65048b7)

**Vote on this feature request**

If you think this feature is valuable, please give this issue a 👍 thumbs up! The more votes, the higher the priority.

**Comment by emocharnik** [comment]
Hi, @pbnj-dragon. Thanks for the request. We're looking with the team on how to make it available in the WEB version too. We'll keep you updated.

**Comment by emocharnik** [comment]
Hi, @pbnj-dragon. The web-compatible extension is released and is ready to be installed. Thanks for the request!
