### ISSUE TITLE
[Bug]: Unable to logout of Scalr in VSCode

### ISSUE THREAD

**Issue by alexUXUI** [Scalr/scalr-vscode#31]
Hey, Scalr team! Thanks so much for all the wonderful work you do.

I noticed that, as far as I can tell, I am unable to switch between Scalr accounts in VSCode.

**Describe the bug**
As a user, I would like to switch between Sclar accounts in VSCode.

I would like to have the option to logout or login from VScode.

I ahve tried uninstalling the extention but when I reinstall it, it loads the previous configs.

I have also tried deleting the Scalr extension from:

```
~/Library/Application\ Support/Code/User/.vscode
```

and no luck with that as well.

**To Reproduce**

1. Go through login flow
2. Connect VSCode to Scalr
3. Try to logout and login with a different Scalr account

**Expected behavior**
There is a way I can login and logout and switch between Scalr accounts, using VSCode extention.

**Screenshots**

**Extension Version (please complete the following information):**

-   Version: .scalr-0.0.5

**VSCode Version:**

-   Version: 1.93.1 

**OS:**

-   OS: macOS 14.4 (23E214)

**Additional context**
My use case is that I have a personal account where I do some prototyping and experimental work and then I want to login to my company account where I can apply changes

Thanks very much in advance for your thoughts on this

**Comment by penja** [comment]
Hello @alexUXUI , thank you for the feedback and for sharing the use case. We should consider improvements to the switching between accounts.

Regarding logout, the login is based on the VS Code session and is available near the accounts icon (see more details on the screen). However, it could be improved by adding a more transparent button or a separate command.

We will come back with improvements or suggestions.

<img width="1227" alt="Screenshot 2024-09-18 at 22 24 29" src="https://github.com/user-attachments/assets/62fac56e-27cc-434a-b521-ef7fd4c9082e">
<img width="754" alt="Screenshot 2024-09-18 at 22 31 30" src="https://github.com/user-attachments/assets/3ad47e94-b605-4021-9241-6ca7ce309977">

**Comment by penja** [comment]
@emocharnik Thoughts?

**Comment by alexUXUI** [comment]
Oh wow! My sincerest apologies, I had no idea that VSCode accounts button existed! I believe this should be all I need!

Thanks so much!
